name: Compile and Upload
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the app
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: app/build/outputs/apk/release/*.apk
